# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-java@v1
      #   with:
      #     java-version: '1.8'
      #     architecture: x64
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
          scope: '@QuadriO'
      - run: npm ci
      - run: npm build
      - run: git add .
      - run: npm test
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Version Bot"
          git config user.email "<>"
      - run: npm run release
      - name: Push tags
        run: |
          git push
          git push --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
